image: node:latest

cache:
  key: node_modules
  paths:
    - node_modules

before_script:
  - mkdir -p ~/.ssh
  - echo "$DEPLOY_SERVER_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - eval "$(ssh-agent -s)"
  - ssh-add ~/.ssh/id_rsa
  - ssh-keyscan -H $DEPLOYMENT_SERVER_IP >> ~/.ssh/known_hosts

stages:
  # - install
  # - build
  - deploy

# install:
#   stage: install
#   only:
#     - master
#   script:
#     - npm install --only=prod
#   artifacts:
#     paths:
#       - node_modules

# build:
#   stage: build
#   only:
#     - master
#   script:
#     - npm run build
#   dependencies:
#     - install
#   artifacts:
#     paths:
#       - build

deploy:
  stage: deploy
  only:
    - master
  script:
    - ssh wsp@$DEPLOYMENT_SERVER_IP "cd salad; ls;"
  # dependencies:
  #   - install
  #   - build
